export const ACTION_TEAM_IS_LOADING = "ACTION_TEAM_IS_LOADING";
export const ACTION_TEAM_HAS_ERRORED = "ACTION_TEAM_HAS_ERRORED";
export const ACTION_TEAM_FETCH_SECCESS = "ACTION_TEAM_FETCH_SECCESS";
