export const ACTION_TEAM_IS_LOADING = "ACTION_TEAM_IS_LOADING";
export const ACTION_TEAM_HAS_ERRORED = "ACTION_TEAM_HAS_ERRORED";
export const ACTION_TEAM_FETCH_SECCESS = "ACTION_TEAM_FETCH_SECCESS";

export const ACTION_ADD_TEAM_DATA = "ACTION_ADD_TEAM_DATA";
